unit_system: "metric"
rapid_wind_interval: 5
debug: "off"
station:
  elevation: 50
  host: "0.0.0.0"
  port: "50222"
mqtt:
  host: "YOUR_MQTT_IP_HERE"
  port: 1883
  username: "YOUR_MQTT_USERNAME_HERE"
  password: "YOUR_MQTT_PASSWORD_HERE"
  debug: "off"
sensors:
