unit_system: "metric" #Use metric or imperial
rapid_wind_interval: 15
weatherflow:
  host: "0.0.0.0"
  port: "50222"
mqtt:
  host: "192.168.1.4"
  port: 1883
  username: "hass_mqtt"
  password: "Shitface.1"
station:
  elevation: 50 # Station Elevation above sea level