sensors:
  - air_density
  - air_temperature
  - battery
  - battery_air
  - dewpoint
  - feelslike
  - illuminance
  - lightning_strike_count
  - lightning_strike_count_today
  - lightning_strike_distance
  - lightning_strike_energy
  - lightning_strike_time
  - precipitation_type
  - rain_rate
  - rain_start_time
  - rain_today
  - rain_yesterday
  - relative_humidity
  - sealevel_pressure
  - solar_radiation
  - station_pressure
  - uptime
  - uv
  - wind_bearing
  - wind_bearing_avg
  - wind_direction
  - wind_direction_avg
  - wind_gust
  - wind_lull
  - wind_speed
  - wind_speed_avg
  