name: publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'


jobs:
  publish-weatherflow2mqtt-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the WeatherFlow2MQTT Docker image
      run: |
        VERSION=$(cat VERSION)
        echo VERSION=$VERSION
        
        docker build . --tag ghcr.io/briis/hass-weatherflow2mqtt:latest --tag ghcr.io/briis/hass-weatherflow2mqtt:$VERSION
        docker create -v $(pwd):/config -p 50222:50222/udp ghcr.io/briis/hass-weatherflow2mqtt:$VERSION
        docker create -v $(pwd):/config -p 50222:50222/udp ghcr.io/briis/hass-weatherflow2mqtt:latest
        docker push ghcr.io/briis/hass-weatherflow2mqtt:$VERSION
        docker push ghcr.io/briis/hass-weatherflow2mqtt:latest
